/**
 * Outfit Actions Utilities
 * Functions for sharing, downloading, and managing outfits
 */

import html2canvas from 'html2canvas';

/**
 * Share outfit to social media or copy link
 */
export const shareOutfit = async (
  platform: 'twitter' | 'facebook' | 'instagram' | 'copy',
  outfitImageUrl: string,
  occasion: string | null
) => {
  const text = `Check out my AI-generated ${occasion || 'outfit'}! ✨`;
  const url = window.location.href;
  const hashtags = 'AIFashion,OutfitAssistant,OOTD';

  switch (platform) {
    case 'twitter':
      window.open(
        `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}&hashtags=${hashtags}`,
        '_blank',
        'width=600,height=400'
      );
      break;

    case 'facebook':
      window.open(
        `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(text)}`,
        '_blank',
        'width=600,height=400'
      );
      break;

    case 'instagram':
      // Instagram doesn't support direct sharing via URL
      // Copy link and show instructions
      await navigator.clipboard.writeText(`${text}\n${url}`);
      alert(
        'Link copied! Open Instagram and paste this in your story or bio.\n\nTip: Screenshot the outfit and share it directly!'
      );
      break;

    case 'copy':
      await navigator.clipboard.writeText(`${text}\n${url}`);
      return 'Link copied to clipboard!';
  }

  return null;
};

/**
 * Download outfit image as PNG
 */
export const downloadOutfitImage = async (imageUrl: string, occasion: string | null) => {
  try {
    // Fetch the image
    const response = await fetch(imageUrl);
    const blob = await response.blob();

    // Create download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const filename = `outfit_${occasion?.toLowerCase().replace(/\s+/g, '_') || 'generated'}_${Date.now()}.png`;

    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Cleanup
    URL.revokeObjectURL(url);

    return 'Outfit downloaded successfully!';
  } catch (error) {
    console.error('Download failed:', error);
    throw new Error('Failed to download outfit. Please try again.');
  }
};

/**
 * Download outfit card as image (entire component with details)
 */
export const downloadOutfitCard = async (elementId: string, occasion: string | null) => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error('Outfit card element not found');
    }

    // Capture the element as canvas
    const canvas = await html2canvas(element, {
      backgroundColor: '#ffffff',
      scale: 2, // Higher quality
      logging: false,
      useCORS: true,
      allowTaint: true,
    });

    // Convert to blob and download
    canvas.toBlob((blob) => {
      if (!blob) {
        throw new Error('Failed to create image');
      }

      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      const filename = `outfit_card_${occasion?.toLowerCase().replace(/\s+/g, '_') || 'generated'}_${Date.now()}.png`;

      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      URL.revokeObjectURL(url);
    }, 'image/png');

    return 'Outfit card downloaded successfully!';
  } catch (error) {
    console.error('Download card failed:', error);
    throw new Error('Failed to download outfit card. Please try again.');
  }
};

/**
 * Copy outfit details to clipboard as text
 */
export const copyOutfitDetails = async (outfitDescription: string, occasion: string | null) => {
  try {
    const parsed = JSON.parse(outfitDescription);

    const text = `
🎨 AI-Generated Outfit ${occasion ? `for ${occasion}` : ''}

✨ Concept: ${parsed.outfit_concept}

👔 Pieces:
${parsed.items
  .map(
    (item: any, idx: number) =>
      `${idx + 1}. ${item.type} - ${item.color}
   ${item.description}
   Style: ${item.style_notes}`
  )
  .join('\n\n')}

🎨 Color Palette: ${parsed.color_palette}

📍 Why This Works: ${parsed.occasion_notes}

🛍️ Shop The Look:
${parsed.product_recommendations
  .map(
    (product: any, idx: number) =>
      `${idx + 1}. ${product.item} by ${product.brand} - ${product.price}
   ${product.description}`
  )
  .join('\n\n')}

---
Generated by AI Outfit Assistant ✨
    `.trim();

    await navigator.clipboard.writeText(text);
    return 'Outfit details copied to clipboard!';
  } catch (error) {
    console.error('Copy failed:', error);
    throw new Error('Failed to copy outfit details. Please try again.');
  }
};

/**
 * Share outfit via Web Share API (mobile native sharing)
 */
export const shareViaWebShare = async (
  outfitImageUrl: string,
  occasion: string | null
): Promise<string> => {
  if (!navigator.share) {
    throw new Error('Web Share API not supported on this device');
  }

  try {
    // Fetch image as blob
    const response = await fetch(outfitImageUrl);
    const blob = await response.blob();
    const file = new File([blob], 'outfit.png', { type: 'image/png' });

    await navigator.share({
      title: `My AI-Generated ${occasion || 'Outfit'}`,
      text: 'Check out my AI-generated outfit! ✨',
      files: [file],
    });

    return 'Outfit shared successfully!';
  } catch (error: any) {
    if (error.name === 'AbortError') {
      // User cancelled sharing
      return 'Sharing cancelled';
    }
    throw new Error('Failed to share outfit. Please try another method.');
  }
};

/**
 * Generate shareable link for outfit
 */
export const generateShareLink = (outfitId: string): string => {
  const baseUrl = window.location.origin;
  return `${baseUrl}?outfit=${outfitId}`;
};

/**
 * Check if Web Share API is supported
 */
export const isWebShareSupported = (): boolean => {
  return navigator.share !== undefined;
};
